mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^',include('polls.urls',namespace="polls")),
    url(r'^',include('registration.backends.default.urls')),
    url(r'^',include('registration.auth_urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/',include('django.contrib.flatpages.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace ='auth')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^search/', include('haystack.urls')),
    
)

polls/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

from polls import views

urlpatterns = patterns('',
                       # ex: /polls/
                       url(r'^$', views.index, name='index'),
                       url(r'^index/$', views.index, name='index'),
                       url(r'^signup/$', views.signup, name='signup'),
                       # ex: /polls/5/
                       url(r'^(?P<poll_id>\d+)/$',
                           views.detail, name='detail'),
                       url(r'^(?P<poll_id>\d+)/load_comments$',
                           views.load_comments, name='load_comments'),
                       # ex: /polls/5/vote/
                       url(r'^(?P<poll_id>\d+)/vote/$',
                           views.vote, name='vote'),
                       url(r'^(?P<poll_id>\d+)/(?P<text_comment>[-\w\W]+)/post_comment/$',
                           views.post_comment, name='post_comment'),
                       url(r'^(?P<poll_id>\d+)/post_comment1/$',
                           views.post_comment1, name='post_comment1'),
                       url(r'^(?P<poll_id>\d+)/ajaxvote/$',
                           'polls.views.ajax_vote'),

                       url(r'^(?P<poll_id>\d+)/login/$',
                           views.login, name='login'),
                       url(r'^(?P<poll_id>\d+)/(?P<comment_text>[-\w\W]+)/login1/$',
                           views.login1, name='login1'),
                       url(r'^login/$', views.login2, name='login2'),
                       url(r'^(?P<poll_id>\d+)/(?P<comment_text>[-\w\W]+)/auth_view/$',
                           views.auth_view, name='auth_view'),
                       url(r'^auth1/$', views.auth_view1, name='auth_view1'),
                       url(r'^logout/$', views.logout, name='logout'),


                       url(r'^(?P<poll_id>\d+)/(?P<comment_text>[-\w\W]+)/register_user/$',
                           views.register_user, name='register_user'),
                       url(r'^register_user1/$', views.register_user1,
                           name='register_user1'),

                       url(r'^(?P<user_id>\d+)/manage_account/$',
                           views.manage_account, name='manage_account'),
                       url(r'^delete_account/$', views.delete_account,
                           name='delete_account'),

                       url(r'^forgotpass/$', views.forgotpass,
                           name='forgotpass'),
                       url(r'^send_forgotpass/$', views.send_forgotpass,
                           name='send_forgotpass'),

                       url(r'^(?P<user_id>\d+)/password_reset/$',
                           views.password_reset, name='password_reset'),
                       url(r'^(?P<user_id>\d+)/password_update/$',
                           views.password_update, name='password_update'),


                       url(r'^passreset/$', auth_views.password_reset,
                           name='forgot_password1'),
                       url(r'^passresetdone/$', auth_views.password_reset_done,
                           name='forgot_password2'),
                       url(r'^passresetconfirm/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$',
                           auth_views.password_reset_confirm, name='forgot_password3'),
                       url(r'^passresetcomplete/$', auth_views.password_reset_complete,
                           name='forgot_password4'),

                       url(r'^password/change/$', auth_views.password_change,
                           name='auth_password_change'),
                       url(r'^password/change/done/$', auth_views.password_change_done,
                           name='auth_password_change_done'),

                       url(r'^(?P<t_id>[\w\W]+)/verification/$',
                           views.verification, name='verification'),

                       url(r'^(?P<user_id>[\w\W]+)/post_ratings/$',
                           views.post_ratings, name='post_ratings'),

                       url(r'^allusers/$', views.allusers, name='allusers'),

                       url(r'^(?P<user_id>\d+)/profile/$',
                           views.profile, name='profile'),
                       #url(r'^/expired/$',views.expired, name='expired'),

                       #url(r'^admin_login/$', views.admin_login, name='admin_login'),
                       )

polls/models.py
from django.db import models
from datetime import date
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from djangoratings.fields import RatingField
from django.db.models import Avg
import math
from django.contrib.sites.models import Site

# Create your models here.


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    rating = models.FloatField()
    expire_date = models.DateTimeField("Expired Date")
    #star_rating = LikertField()

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def sort_by_rating(self):
        print timezone.now()
        p1 = Ratings.objects.all().filter(poll_id=1).aggregate(Avg('rating'))
        p2 = Ratings.objects.all().filter(poll_id=2).aggregate(Avg('rating'))
        p3 = Ratings.objects.all().filter(poll_id=3).aggregate(Avg('rating'))
        print 'test1'
        pid1 = Poll.objects.get(pk=1)
        pid2 = Poll.objects.get(pk=2)
        pid3 = Poll.objects.get(pk=3)
        print 'test2'
        pid1.rating = p1['rating__avg']
        pid2.rating = p2['rating__avg']
        pid3.rating = p3['rating__avg']
        print 'test3'
        pid1.save()
        pid2.save()
        pid3.save()
        print 'test4'
        poll1 = Ratings.objects.all().filter(
            poll_id=self).aggregate(Avg('rating'))
        return poll1['rating__avg']
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    sort_by_rating.short_description = 'Ratings for Polls'
    sort_by_rating.admin_order_field = 'rating'

    def get_absolute_url(self):
        return u"/polls/%s/" % self.pk


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    #sites = models.ManyToManyField(Site)

    def __unicode__(self):
        return self.choice_text


class Comment(models.Model):
    poll = models.ForeignKey(Poll)
    comment = models.CharField(max_length=1000)
    user_id = models.IntegerField(max_length=11)
    username = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=75)
    date_joined = models.DateTimeField()

    def __unicode__(self):
        return self.comment

    def save_comment(self, comment_text, poll_id):
        p = Poll.objects.get(pk=poll_id)
        p.comment_set.create(comment=comment_text, poll_id=poll_id)


class Vote(models.Model):
    poll = models.ForeignKey(Poll)
    user_name = models.CharField(max_length=32)

    def __unicode__(self):
        return self.user_name


class Tokens(models.Model):
    token_id = models.CharField(max_length=60)
    user_id = models.ForeignKey(User)

    def __unicode__(self):
        return self.token_id


class UserProfilePic(models.Model):
    user = models.OneToOneField(User)
    profile_photo = models.ImageField(upload_to='profiles')

    def __str__(self):
        return "%s's profile" % self.user


class Ratings(models.Model):
    poll = models.ForeignKey(Poll)
    rate_user = models.CharField(max_length=32)
    rating = models.IntegerField(max_length=5)

    def __unicode__(self):
        return self.rate_user


def deactive_poll(self):
    polls = Poll.objects.all()
    print polls
    for poll in polls:
        print poll.pub_date
        print poll.expire_date
        if timezone.now() < poll.expire_date:
            print 'Polls is in active'
            return true
        else:
            print 'poll is in deactive'
            return false

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class MyRegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=30)

    def __init__(self, *args, **kwargs):
        super(MyRegistrationForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['username'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True

    def clean_username(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.username
        else:
            return self.cleaned_data['username']

    def clean_email(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.email:
            return instance.email
        else:
            return self.cleaned_data['email']

    class Meta:
        model = User
        fields = ('username', 'email', 'password1',
                  'password2', 'first_name', 'last_name')

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.password1 = self.cleaned_data['password1']
        user.password2 = self.cleaned_data['password2']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_active = 0

        if commit:
            user.save()

        return user


class PasswordResetForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=30)

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['username'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields['first_name'].widget.attrs['first_name'] = True
            self.fields['last_name'].widget.attrs['last_name'] = True

    def clean_username(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.username
        else:
            return self.cleaned_data['username']

    def clean_email(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.email:
            return instance.email
        else:
            return self.cleaned_data['email']

    def clean_first_name(self):
        instance = getattr(self, 'instance', None)
        if instance and instace.pk:
            return instance.first_name
        else:
            return self.cleaned_data['first_name']

    def clean_last_name(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.last_name:
            return instance.last_name
        else:
            return self.cleaned_data['last_name']

    class Meta:
        model = User
        fields = ('username', 'email', 'password1',
                  'password2', 'first_name', 'last_name')

    def save(self, commit=True):
        user = Super(MyRegistrationForm, self).save(commit=False)
        user.password1 = self.cleaned_data['password1']
        user.password2 = self.cleaned_data['password2']
        if commit:
            user.save()
            return user

polls/templates/polls/detail.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
    {% block content %}
    {% load staticfiles %}
    <head>
	    <title>{% block title %}choices for question{% endblock %}</title>
	    <meta></meta>
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
        <link href="{% static 'polls/css/3.css' %}" rel="stylesheet" media="screen">
        <link rel="stylesheet" type="text/css" href="{% static 'polls/css/jquery-ui.css' %}" />
		<link rel="stylesheet" href="{% static 'polls/css/style1.css' %}">
		<script src="{% static 'polls/js/jquery-1.10.2.js' %}"></script>
		<script src="{% static 'polls/js/bootstrap.js' %}"></script>
		<script src="{% static 'polls/js/jquery-ui.js' %}"></script>
		<script>
  $(function() {
    $(document).tooltip({
   content: function () {
     return ( ( $( this ).prop( 'title' ).replace( '|', '<br />' ) ) );
   }
});
    $( document ).tooltip({
      position: {
        my: "left bottom-20",
        at: "left top",
        using: function( position, feedback ) {
          $( this ).css( position );
          $( "<div>" )
            .addClass( "arrow" )
            .addClass( feedback.vertical )
            .addClass( feedback.horizontal )
            .appendTo( this );
        }
      }
    });
  });
  </script>
  <style>
	  img {
	alt:"award icon";
	width:18px;
	height:18px;
	}
  .ui-tooltip, .arrow:after {
    background: black;
    border: 2px solid white;
  }
  .ui-tooltip {
    padding: 10px 20px;
    color: white;
    border-radius: 20px;
    font: bold 14px "Helvetica Neue", Sans-Serif;
    text-transform: uppercase;
    box-shadow: 0 0 7px black;
    max-width:400px;
  }
  .arrow {
    width: 70px;
    height: 16px;
    overflow: hidden;
    position: absolute;
    left: 50%;
    margin-left: -35px;
    bottom: -16px;
  }
  .arrow.top {
    top: -16px;
    bottom: auto;
  }
  .arrow.left {
    left: 20%;
  }
  .arrow:after {
    content: "";
    position: absolute;
    left: 20px;
    top: -20px;
    width: 25px;
    height: 25px;
    box-shadow: 6px 5px 9px -9px black;
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    tranform: rotate(45deg);
  }
  .arrow.top:after {
    bottom: -20px;
    top: auto;
  }
  
  .rmk{
 margin-bottom:50px;
  }
  .center{
	  text-align:center;
  }
  </style>
  
	</head>
	<body>
		<div class="container">
		<div class="row navbar-fixed-top" id='header'>
			<div class="col-md-8"></div>
			<div class="col-md-4"><a href="{% url 'polls:index' %}"><h1>Polls & Choices</h1></a></div>
		</div>
		<div class="row" id="nav">
		<div id="vote_fail" class="alert alert-danger alert-dismissable">
			  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			  <strong>Fail!</strong> You Have Submitted the Vote Already.
		</div>
		<div id="vote_success" class="alert alert-success alert-dismissable">
			  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			  <strong>Success!</strong> Vote Submitted Successfully.
		</div>
		</div>
		<div class="row wite">
		<div class="col-md-10"><h1>{{poll.question}}</h1></div>
		<div class="col-md-2"></div>
		</div>
		<div class="row wite">
			<div class="col-md-4">
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		<form action="" method="post" name="form1">
			{% csrf_token %}
			{% for choice in poll.choice_set.all %}
				<div class="radio">
				<input type="radio" name="choice{{poll.id}}" id="choice{{ forloop.counter }}" value = "{{ choice.id }}" />
				<lable for="choice{{ forloop.counter }}" id="txt">{{choice.choice_text}}-- <span id="{{choice.id}}">{{ choice.votes }} </span>&nbsp;vote{{ choice.votes|pluralize }}<span id="test{{choice.id}}"></span></lable><br />
				</div>
			{% endfor %}
			<div class="form-group">
			<div>
			<input type="submit" value="Vote" id="vote{{poll.id}}" class="btn btn-success " />
			</div>
			</div>
		</form>
		</div>
		<div class="col-md-4"></div>
		<div class="col-md-4"></div>
		</div>
		<div class="row wite">
		<div class="col-md-8"><h2>You can comment here about the Poll</h2></div>
		<div class="col-md-2"></div>
		<div class="col-md-2"></div>
		</div>
		<div class="row wite">
			<div class="col-md-8">
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		<form role="form" action="{% if user.is_authenticated %}
			{% url 'polls:post_comment1' poll.id %}{% else %}{% url 'polls:login' poll.id %}{% endif %}" method="post" >{% csrf_token %}
			<div class="form-group">
			<textarea name="comment" id ="comment" placeholder="write your Comment here.." rows="4" cols="40" class="form-control" required></textarea>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-8 col-sm-4">
			<input type="submit" value="Comment" class="btn btn-success btn-block" id="post" data-toggle="tooltip" data-placement="top"   />
			</div>
			</div>
		</form>
		</div>
		<div class="col-md-2"></div>
		<div class="col-md-2"></div>
		</div>
		<div class="row rmk wite">
			<h2>Comments posted by users</h2>
		<ul id="comments" class="example">
			{% for comment in comments %}
			<div class="pwite">
				<li class="user opener">{{comment.username}}:</a></li>
				<li data-toggle="tooltip" data-placement="top" title="UserName: {{comment.username}}&#13;<br/>
				First-Name: {{comment.first_name}}&#13;<br/>
				Last-Name: {{comment.last_name}}&#13;<br/>
				E-Mail:{{comment.email}}&#13;<br/>
				Joined on:{{comment.date_joined}}" >{{ comment.comment }}</li>
			</div>
			{% endfor %}
		</ul>
		<div class="pagination">
			<span class="step-links">
			{% if comments.has_next %}
		    <a data-toggle="tooltip" title="more.." class="btn btn-info" id="ajax-call"  href="{% url 'polls:load_comments' poll.id %}?page={{ comments.next_page_number }}">Load More</a>
			{% endif %}
			</span>
		</div>
		</div>
		<div class="row">
			<nav class="navbar navbar-default navbar-fixed-bottom" id="footer" role="navigation">
			<a class="navbar-brand" href="{% url 'polls:index' %}">Home</a>
			<p class="navbar-text navbar-right">© 2014 Nyros Technologies. All Rights Reserved.</p>
			</nav>
		</div>
<div class="modal"><!-- Place at bottom of page --></div>
		</div>
	<script type="text/javascript">
		$(document).ready(function(){
		$("#post").click(function(){
			{% if user.is_authenticated %}
		    return true;
		    {% else %}
		    alert("You need to login first,if not registered register")
		    {% endif %}
		});
		$("#vote_fail").hide()
		$("#vote_success").hide()
		$("#ajax-call").click(function(e){
			e.preventDefault();
			$that = $(this)
			$.ajax({
				url:this.href,
				type: 'GET',
				dataType: 'json',
				success:function(result){
			        lis = "";
			        window.rs = result
			        poll_id = +result.details[1]
			        //alert(result.details[0])
			        if (result.details[0]){
			        $that.attr('href', '/'+poll_id+'/load_comments?page='+result.details[0])
				}
				else{
					$that.remove()
					}
					$.each(JSON.parse(result.comments), function(index, items){
						lis += "<div class='pwite'><li class='user'>"+items.object[4]+":</li><li title='UserName:"+items.object[4]+"<br/>FirstName:"+items.object[5]+"<br/>LastName:"+items.object[6]+"<br/>E-Mail:"+items.object[7]+"'>"+items.object[0]+"</li></div>"
						console.log(items.object[0]);
						});
       $("#comments").append(lis)
  }
				});
	});
			var create_vote{{poll.id}} = function() {
			var value = $("form input[name='choice{{poll.id}}']:checked").val()
			if(value!="")
			{
				var data={choice:value};
				
				var args={type:"POST", url:"/{{poll.id}}/ajaxvote/",data:data,success:create_vote_complete{{poll.id}},dataType: 'html'};
				
				$.ajax(args);
			}
			else
			{
				//some message here
			}
			return false;
		};
		$("#vote{{poll.id}}").click(create_vote{{poll.id}});
		
	var create_vote_complete{{poll.id}} = function(res,status,jqXHR){
			if(status=="success"){
				var value = $("form input[name='choice{{poll.id}}']:checked").val()
				num = $("#"+value).text()
				num = parseInt(num);
				if (res==num)
				{
					$("#vote_fail").show()
					$("form input[name='choice{{poll.id}}']:checked").prop('checked',false);
				}
				else{
					$("#"+value).html(res+"&nbsp;");
					$("#vote_success").show()
					$("form input[name='choice{{poll.id}}']:checked").prop('checked',false);
				}
				x = document.form1.choice{{poll.id}}
				z = new Array();
				novotes = new Array();
				for(var i=0;i<x.length;i++)
				{
				z[i] = x[i].value;
				novotes[i] = parseInt($("#"+z[i]).text());
			    }
			    var maximum = Math.max.apply(Math,novotes)
			    //alert(maximum);
			    for(k=0;k<z.length;k++)
			    {
					if (maximum==parseInt($("#"+z[k]).text()))
					{
						$("#test"+z[k]).html('<img src="{% static "polls/images/icon.png" %}" alt="Winner"></img>');
					}
					else
					{
						$("#test"+z[k]).html("&nbsp");
					}
				}
				//window.location.href="/polls/"
			}
			else
			{
				//display_message(res.responseText,$(".message"));
				alert("You didn't select a choice to vote");
			}
		}	
});
        
		
	function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
        // or any other URL that isn't scheme relative or absolute i.e relative.
        !(/^(\/\/|http:|https:).*/.test(url));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
            // Send the token to same-origin, relative URLs only.
            // Send the token only if the method warrants CSRF protection
            // Using the CSRFToken value acquired earlier
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
$(document).ready(function(){
	x = document.form1.choice{{poll.id}}
				z = new Array();
				novotes = new Array();
				for(var i=0;i<x.length;i++)
				{
				z[i] = x[i].value;
				novotes[i] = parseInt($("#"+z[i]).text());
			    }
			    var maximum = Math.max.apply(Math,novotes)
			    //alert(maximum);
			    for(k=0;k<z.length;k++)
			    {
					if (maximum==parseInt($("#"+z[k]).text()))
					{
						$("#test"+z[k]).html('<img src="{% static "polls/images/icon.png" %}" alt="Winner"></img>');
					}
					else
					{
						$("#test"+z[k]).html("&nbsp");
					}
				}
			});
			
$body = $("body");
$(document).on({
    ajaxStart: function() { $body.addClass("loading");    },
     ajaxStop: function() { $body.removeClass("loading"); }    
});
	
</script>
</body>
</html>
{% endblock %}

polls/templates/polls/login.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<link href="{% static 'polls/css/3.css' %}" rel="stylesheet" media="screen">
<script src="{% static 'polls/bootstrap.min.js' %}"></script>
<script src="{% static 'polls/js/jquery-1.10.2.js' %}"></script>
<style>
	h1{
		text-align:center;
	}
	.container{
		margin:0px;
		padding:auto;
		margin-left:auto;
		margin-right:auto;
	}
</style>
</head>
<body>
<div class="container">
		<div class="row navbar-fixed-top" id='header'>
			<div class="col-md-8"></div>
			<div class="col-md-4"><a href="{% url 'polls:index' %}" ><h1>Polls & Choices</h1></a></div>
		</div>
	<div class="row" id="nav">
    {% if form.errors %}
        <p class="error">Sorry, That's not a valid username or password</p>
    {% endif %}
    </div>
    <div class="row">
    <div class="col-md-4"></div>
  <div class="col-md-4"><p>If already registered Sign In or <a href="{% url 'polls:register_user1' %}">Sign Up</a></p>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}</div>
  <div class="col-md-4"></div>
    
    </div>
    <form class="form-horizontal" role="form" action="{% url 'polls:auth_view' poll.id comment_text %}" method="post">{% csrf_token %}
<div class="form-group">
		<label  for="username" class="col-sm-4 control-label">Username:</label> 
		 <div class="col-sm-4"><input id="username" maxlength="30" name="username" type="text" value = "{{u_name|default:''}}" class="form-control" placeholder="Username" required /></div>
		<div class="col-sm-4">{{ form.username.errors }}</div>
	</div>
    <div class="form-group">
		<label  for="password" class="col-sm-4 control-label">Password:</label> 
		<div class="col-sm-4"><input id="password" name="password" value="{{pwd|default:''}}" type="password" placeholder="Enter Password" class="form-control" required/></div> 
		<div class="col-sm-4">{{ form.password1.errors }}</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
		<div class="checkbox">
        <label>
          <input type='checkbox' name="remember_me" /> Remember me
        </label>
		</div>
		</div>
	</div>
        <div class="form-group">
			<div class="col-sm-offset-4 col-sm-3"><a href="{% url 'polls:forgotpass' %}">Forgot Password?</a></div>
			<div class="col-sm-2"><input type="submit" value="Sign In" class="btn btn-success" /></div>
		</div>
        
        <input type="hidden" name="next" value="{{ next|escape }}" />
    </table>
    </form>
    <div class="row">
			<nav class="navbar navbar-default navbar-fixed-bottom" id="footer" role="navigation">
			<a class="navbar-brand" href="{% url 'polls:index' %}">Home</a>
			<p class="navbar-text navbar-right">© 2014 Nyros Technologies. All Rights Reserved.</p>
			</nav>
		</div>
</div>
    </body>
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}
{% block content %}
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

{% endblock %}